### ISSUE TITLE
M3C multiview consensus cluster

### ISSUE THREAD

**Issue by hiblerw2** [behnam-yousefi/ConsensusClustering#2]
I found this package to be immensely helpful, thank you so much! I noticed that this package included an R script that was specific to M3C functions. Would it be possible to update the multiview_consensus_matrix() function so that it could accommodate M3C clustering on multi-view/cohort studies?

**Comment by behnam-yousefi** [comment]
Thank you so much for your kind words and you interest!
M3C is a type of "data perturbation consensus clustering (CC)" and implementing it as a multi-data CC is not super intuitive for us. Moreover, our package does not use any code from M3C, so I removed the M3C file from the repository to avoid any confusion. It is also worth noting that we only used M3C for comparison in our manuscript on bioRxiv (see Figure 3), and we showed that "LogitScore" is preferable over M3C's robustness score.
